export const courseData = [
  {
    sectionTitle: "Welcome to Full-Stack Engineer Path",
    sectionValue: "Welcome to Full-Stack Engineer Path",
    sectionNumber:1,
    sectionId: "Welcome-to-full-stack-engineer-path",
    sectionDescription:
      "Welcome to the Full-Stack Engineer Career Path! Get an overview of the journey ahead of you, save some helpful resources, and join our community. Then dive into the field of web development and the exciting opportunities ahead.",
    sectionTopics: [
      {
        section_topic_title: "Introduction: Overview of Web Development",
        section_topic_description: "Introduction: Overview of Web Development",
        section_topic_id: "Introduction:Overview-of-web-development",
        type: "video",
        videoId: "https://player.vimeo.com/video/802171967?h=806509b5ca",
        videoLength:12,
      },
      {
        section_topic_title: "The Internet And Web Development",
        section_topic_description:
          "Learn about the history of the internet and get an overview of the tools developers use to create websites.",
        section_topic_id: "The-Internet-And-Web-Development-Description",
        type: "video",
        videoId: "https://player.vimeo.com/video/802171627?h=1662f1c4d6",
        videoLength:12,
      },
      {
        section_topic_title: "Introduction to Software Engineering",
        section_topic_description:
          "Understand the basics of programming, software engineering, and the difference between front-end and back-end (and full-stack!)",
        section_topic_id: "Introduction-to-Software-Engineering",
        type: "video",
        videoId: "https://player.vimeo.com/video/802171967?h=806509b5ca",
        videoLength:12,
      },
      {
        section_topic_title: "Overview of Web Development",
        sub_topic_description:
          "Review what you've learned in the Overview of Web Development Unit.",
        sub_topic_id: "Overview-of-Web-Development",
        type: "video",
        videoId: "https://player.vimeo.com/video/802171627?h=1662f1c4d6",
        videoLength:12,
      },
    ],
  },
  {
    sectionTitle: "Fundamentals of HTML",
    sectionValue: "Fundamentals of HTML",
    sectionNumber:2,
    sectionId: "Fundamentals-of-HTML",
    sectionDescription:
      "HTML provides the structure for all web pages you visit. Learn the elements that you'll use to piece together this structure and best semantic practices associated with building out a web page.",
    sectionTopics: [
      {
        section_topic_title: "Introduction: Fundamentals of HTML",
        section_topic_description: "Introduction: Fundamentals of HTML",
        section_topic_id: "Introduction:-Fundamentals-of-HTML",
        type: "video",
        videoId: "Introduction:-Fundamentals-of-HTML-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Learn HTML: Elements",
        section_topic_description: "Learn HTML: Elements",
        section_topic_id: "Learn-HTML:-Elements",
        type: "video",
        videoId: "Learn HTML: Elements-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Learn HTML: Structure",
        section_topic_description: "Learn HTML: Structure",
        section_topic_id: "Learn-HTML:-Structure",
        type: "video",
        videoId: "Learn-HTML:-Structure-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Learn HTML: Tables",
        section_topic_description: "Learn HTML: Tables",
        section_topic_id: "Learn-HTML:-Tables",
        type: "video",
        videoId: "Learn-HTML:-Tables-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Semantic HTML",
        section_topic_description: "Semantic HTML",
        section_topic_id: "Semantic HTML",
        type: "video",
        videoId: "Semantic-HTML-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Review: Fundamentals of HTML",
        section_topic_description: "Review: Fundamentals of HTML",
        section_topic_id: "Review:-Fundamentals-of-HTML",
        type: "video",
        videoId: "Review:-Fundamentals-of-HTML-videoId",
        videoLength:12,
      },
    ],
  },
  {
    sectionTitle: "Fundamentals of CSS",
    sectionValue: "Fundamentals of CSS",
    sectionNumber:3,
    sectionId: "Fundamentals-of-CSS",
    sectionDescription:
      "Add some flair to your sites with Cascading Style Sheets (CSS). You'll learn the fundamentals, which include: how to create rulesets, styling, position, layouts, and more to make your sites stand out.",
    sectionTopics: [
      {
        section_topic_title: "Introduction: Fundamentals of CSS",
        section_topic_description: "Introduction: Fundamentals of CSS",
        section_topic_id: "Introduction:-Fundamentals-of-CSS",
        type: "video",
        videoId: "Introduction:-Fundamentals-of-CSS-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Learn CSS: Selectors and Visual Rules",
        section_topic_description: "Learn CSS: Selectors and Visual Rules",
        section_topic_id: "Learn-CSS:-Selectors-and-Visual-Rules",
        type: "video",
        videoId: "Learn-CSS:-Selectors-and-Visual-Rules",
        videoLength:12,
      },
      {
        section_topic_title: "Learn CSS: The Box Model",
        section_topic_description: "Learn how to use the Box Model to position HTML elements on a web page.",
        section_topic_id: "Learn-CSS:-The-Box-Model",
        type: "video",
        videoId: "Learn-CSS:-The-Box-Model-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Learn CSS: Display and Positioning",
        section_topic_description: "Learn CSS rules for displaying and positioning elements on a web page.",
        section_topic_id: "Learn-CSS:-Display-and-Positioning",
        type: "video",
        videoId: "Learn-CSS:-Display-and-Positioning-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Review: Fundamentals of CSS",
        section_topic_description: "Review what was covered in the Fundamentals of CSS Unit.",
        section_topic_id: "Review:-Fundamentals-of-CSS",
        type: "video",
        videoId: "Review:-Fundamentals-of-CSS-videoId",
        videoLength:12,
      },
    ],
  },
  {
    sectionTitle: "Developing Websites Locally",
    sectionValue: "Developing Websites Locally",
    sectionNumber:4,
    sectionId: "Developing-Websites-Locally",
    sectionDescription:
      "Part of becoming a developer means you'll need the skills to create websites on your own computer. Use tools like text editors and Chrome Devtools to work out how to build websites locally.",
    sectionTopics: [
      {
        section_topic_title: "Introduction: Developing Websites Locally",
        section_topic_description: "Introduction: Developing Websites Locally",
        section_topic_id: "Introduction:-Developing-Websites-Locally",
        type: "video",
        videoId: "Introduction:-Developing-Websites-Locally-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Getting Started with Text Editors",
        section_topic_description: "Learn to get set up with text editors.",
        section_topic_id: "Getting-Started-with-Text-Editors",
        type: "video",
        videoId: "Getting-Started-with-Text-Editors-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Intro to Chrome Devtools",
        section_topic_description: "Learn how to inspect web pages in the browser and add CSS to your website.",
        section_topic_id: "Intro to Chrome Devtools",
        type: "video",
        videoId: "Intro to Chrome Devtools-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Review: Developing Websites Locally",
        section_topic_description: "Review what was covered in the Developing Websites Locally Unit.",
        section_topic_id: "Review: Developing Websites Locally",
        type: "video",
        videoId: "Review:-Developing-Websites-Locally-videoId",
        videoLength:12,
      }
    ],
  },
  {
    sectionTitle: "Deploying Websites",
    sectionValue: "Deploying Websites",
    sectionNumber:5,
    sectionId: "Developing-Websites-Locally",
    sectionDescription:
      "Once you have your site, you'll want to share it — which means you'll need to host and deploy it. Use the command line and GitHub pages to make this deployment process seamless.",
    sectionTopics: [
      {
        section_topic_title: "Introduction: Developing Websites",
        section_topic_description: "Introduction: Developing Websites",
        section_topic_id: "Introduction:-Developing-Websites",
        type: "video",
        videoId: "Introduction:-Developing-Websites-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Web Hosting",
        section_topic_description: "Learn how to host your website and set up a custom domain.",
        section_topic_id: "Web Hosting",
        type: "video",
        videoId: "Web Hosting-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Deploy a site with Github Pages",
        section_topic_description: "Learn how to deploy a static website with Github Pages.",
        section_topic_id: "Deploy a site with Github Pages",
        type: "video",
        videoId: "Deploy a site with Github Pages-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Command Line for Building Websites",
        section_topic_description: "Learn the basics of the command line to set up website files on your own computer.",
        section_topic_id: "Command Line for Building Websites",
        type: "video",
        videoId: "Command Line for Building Websites-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Review: Deploying Websites",
        section_topic_description: "Review what was covered in the Deploying Websites Unit.",
        section_topic_id: "Review: Deploying Websites",
        type: "video",
        videoId: "Review: Deploying Websites-videoId",
        videoLength:12,
      }
    ],
  },
  {
    sectionTitle: "Improved Styling with CSS",
    sectionValue: "Improved Styling with CSS",
    sectionNumber:6,
    sectionId: "Improved Styling with CSS-Id",
    sectionDescription:
      "Learn how to incorporate colors, typography, links, buttons, and more to take your CSS to the next level. Then take your skills and incorporate wireframing to provide a vision for your site.",
    sectionTopics: [
      {
        section_topic_title: "Introduction: Improved Styling with CSS",
        section_topic_description: "Introduction: Improved Styling with CSS",
        section_topic_id: "Introduction: Improved Styling with CSS-id",
        type: "video",
        videoId: "Introduction: Improved Styling with CSS-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Learn CSS: Colors",
        section_topic_description: "Learn all about choosing and setting CSS colors using a variety of techniques.",
        section_topic_id: "Learn CSS: Colors-id",
        type: "video",
        videoId: "Learn CSS: Colors-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Learn CSS: Typography",
        section_topic_description: "Learn all about CSS typography, such as how to include fonts from other sources and how to style your text.",
        section_topic_id: "Learn CSS: Typography",
        type: "video",
        videoId: "Learn CSS: Typography-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Learn Links and Buttons",
        section_topic_description: "Learn best practices and implementations for demonstrating interaction and interactivity to your website’s visitors.",
        section_topic_id: "Learn Links and Buttons",
        type: "video",
        videoId: "Learn Links and Buttons-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Learn Secondary Navigation",
        section_topic_description: "Learn how to use breadcrumbs in your website design.",
        section_topic_id: "Learn Secondary Navigation",
        type: "video",
        videoId: "Learn Secondary Navigation-videoId",
        videoLength:12,
      },{
        section_topic_title: "Wireframing",
        section_topic_description: "Learn about wireframing - a quick way to sketch out website architecture.",
        section_topic_id: "Wireframing",
        type: "video",
        videoId: "Wireframing-videoId",
        videoLength:12,
      },{
        section_topic_title:"Review: Improved Styling with CSS",
        section_topic_description: "Review what was covered in the Improved Styling with CSS Unit.",
        section_topic_id:"Review: Improved Styling with CSS",
        type: "video",
        videoId:"Review: Improved Styling with CSS-videoId",
        videoLength:12,
      }
    ],
  },
  {
    sectionTitle: "Making a Website Responsive",
    sectionValue: "Making a Website Responsive",
    sectionNumber:7,
    sectionId: "Making a Website Responsive-Id",
    sectionDescription:
      "Sites show up on all different types of devices, like: desktops, cellphones, laptops, etc. Incorporate responsive design to create a site that adapts to your users' different screen sizes.",
    sectionTopics: [
      {
        section_topic_title: "Introduction: Making a website responsive",
        section_topic_description: "Introduction: Making a website responsive",
        section_topic_id: "Introduction: Making a website responsive-id",
        type: "video",
        videoId: "Introduction: Making a website responsive-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Learn Responsive Design: Grids and Spacing",
        section_topic_description: "Learn how designers use grids to create flexible page layouts.",
        section_topic_id: "Learn Responsive Design: Grids and Spacing-id",
        type: "video",
        videoId: "Learn Responsive Design: Grids and Spacing-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Learn with Flexbox",
        section_topic_description: "Learn CSS Flexbox to create flexible page layouts.",
        section_topic_id: "Learn with Flexbox",
        type: "video",
        videoId: "Learn with Flexbox-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Learn CSS: Grid",
        section_topic_description: "Learn CSS Grid to create flexible page layouts.",
        section_topic_id: "Learn CSS: Grid",
        type: "video",
        videoId: "Learn CSS: Grid-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Learn Responsive Design",
        section_topic_description: "Learn responsive design techniques, like relative sizing units and media queries, to create websites viewable on devices of all sizes.",
        section_topic_id: "Learn Responsive Design",
        type: "video",
        videoId: "Learn Responsive Design-videoId",
        videoLength:12,
      },{
        section_topic_title: "Learn CSS: Documentation & Debugging",
        section_topic_description: "Learn how to look up things that you don’t know in official documentation so that you can solve problems independently!",
        section_topic_id: "Learn CSS: Documentation & Debugging",
        type: "video",
        videoId: "Learn CSS: Documentation & Debugging-videoId",
        videoLength:12,
      },{
        section_topic_title:"Review: Making a website Responsive",
        section_topic_description: "Review what was covered in the Making a Website Responsive Unit.",
        section_topic_id:"Review: Making a website Responsive",
        type: "video",
        videoId:"Review: Making a website Responsive-videoId",
        videoLength:12,
      }
    ],
  },
  {
    sectionTitle: "JavaScript Syntax, Part I",
    sectionValue: "JavaScript Syntax, Part I",
    sectionNumber:8,
    sectionId: "JavaScript Syntax, Part I-Id",
    sectionDescription:
      "JavaScript enpowers you to add logic to your website and create a truely interactive site. Start with the basics of variables, data types, conditionals, functions, and scope.",
    sectionTopics: [
      {
        section_topic_title: "Introduction: Javascript Syntax, Part 1",
        section_topic_description: "Get introduced to JavaScript and get comfortable with the basics of writing JavaScript programs.",
        section_topic_id: "Introduction: Javascript Syntax, Part 1-id",
        type: "video",
        videoId: "Introduction: Javascript Syntax, Part 1-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Introduction to Javascript",
        section_topic_description: "Understand how JavaScript plays a significant role in web development.",
        section_topic_id: "Introduction to Javascript-id",
        type: "video",
        videoId: "Introduction to Javascript-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Learn Javascript Syntax: Introduction",
        section_topic_description: "In this course, you will learn about JavaScript data types, built-in methods, and variables.",
        section_topic_id: "Learn Javascript Syntax: Introduction",
        type: "video",
        videoId: "Learn Javascript Syntax: Introduction-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Learn Javascript Syntax: Conditionals",
        section_topic_description: "Learn how to use if, else if, else, switch, and ternary syntax to control the flow of a program in JavaScript.",
        section_topic_id: "Learn Javascript Syntax: Conditionals",
        type: "video",
        videoId: "Learn Javascript Syntax: Conditionals-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Learn Javascript Syntax: Funcations",
        section_topic_description: "Learn about JavaScript function syntax, passing data to functions, the return keyword, ES6 arrow functions, and concise body syntax.",
        section_topic_id: "Learn Javascript Syntax: Funcations",
        type: "video",
        videoId: "Learn Javascript Syntax: Funcations-videoId",
        videoLength:12,
      },{
        section_topic_title: "Learn Javascript Syntax: Scope",
        section_topic_description: "Learn about global and block level scope in JavaScript.",
        section_topic_id: "Learn Javascript Syntax: Scope",
        type: "video",
        videoId: "Learn Javascript Syntax: Scope-videoId",
        videoLength:12,
      },{
        section_topic_title:"Practice Javascript Syntax: Variables, Datatypes, variables, functions",
        section_topic_description: "Practice using the JavaScript syntax that you’ve just learned.",
        section_topic_id:"Practice Javascript Syntax: Variables, Datatypes, variables, functions",
        type: "video",
        videoId:"Practice Javascript Syntax: Variables, Datatypes, variables, functions-videoId",
        videoLength:12,
      }
    ],
  },
  {
    sectionTitle: "JavaScript Syntax, Part II",
    sectionValue: "JavaScript Syntax, Part II",
    sectionNumber:9,
    sectionId: "JavaScript Syntax, Part II-Id",
    sectionDescription:
      "Build off your knowledge of JavaScript to implement even more functionality. Learn to utilize arrays, loops, objects, interators, errors, and debugging.",
    sectionTopics: [
      {
        section_topic_title: "Introduction: Javascript Syntax, Part || ",
        section_topic_description: "See What's covered in the Javascript Syntax, part || unit",
        section_topic_id: "Introduction: Javascript Syntax, Part || -id",
        type: "video",
        videoId: "Introduction: Javascript Syntax, Part || -videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Learn Javascript Syntax: Arrays",
        section_topic_description: "In this course, you will learn about arrays, a data structure in JavaScript used to store lists of data.",
        section_topic_id: "Learn Javascript Syntax: Arrays-id",
        type: "video",
        videoId: "Learn Javascript Syntax: Arrays-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Learn Javascript Syntax: Loops",
        section_topic_description: "In this course, you will learn how to use for and while loops to execute blocks of code multiple times.",
        section_topic_id: "Learn Javascript Syntax: Loops",
        type: "video",
        videoId: "Learn Javascript Syntax: Loops-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Learn Javascript Syntax: Objects",
        section_topic_description: "Learn about JavaScript ES6 object syntax to model real-world items. Objects, advanced Objects, documentation: JavaScript Objects",
        section_topic_id: "Learn Javascript Syntax: Objects",
        type: "video",
        videoId: "Learn Javascript Syntax: Objects-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Learn Javascript Syntax: Iterators",
        section_topic_description: "n this course, you will learn how to use iterator methods to simplify the process of looping over arrays. Higher Order Functions",
        section_topic_id: "Learn Javascript Syntax: Iterators",
        type: "video",
        videoId: "Learn Javascript Syntax: Iterators-videoId",
        videoLength:12,
      },{
        section_topic_title: "Learn Javascript Syntax: Errors and Debugging",
        section_topic_description: "Learn how to address errors in this course all about JavaScript errors!",
        section_topic_id: "Learn Javascript Syntax: Errors and Debugging",
        type: "video",
        videoId: "Learn Javascript Syntax: Errors and Debugging-videoId",
        videoLength:12,
      },{
        section_topic_title:"Practice Javascript Syntax: Arrays, loops, objects, iterators",
        section_topic_description: "Practice what you've learned with JavaScript Syntax.",
        section_topic_id:"Practice Javascript Syntax: Arrays, loops, objects, iterators",
        type: "video",
        videoId:"Practice Javascript Syntax: Arrays, loops, objects, iterators-videoId",
        videoLength:12,
      }
    ],
  },
  {
    sectionTitle: "JavaScript Testing",
    sectionValue: "JavaScript Testing",
    sectionNumber:10,
    sectionId: "JavaScript Testing-Id",
    sectionDescription:
      "Testing ensures that your app performs as intended. Learn how to create Mocha tests and the Test Driven Development (TDD) methodology that demonstrates how testing can be applied.",
    sectionTopics: [
      {
        section_topic_title: "Introduction: Javascript Testing ",
        section_topic_description: "See what's covered in the JavaScript Testing Unit.",
        section_topic_id: "Introduction: Javascript Testing -id",
        type: "video",
        videoId: "Introduction: Javascript Testing -videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Why Tests",
        section_topic_description: "Learn about testing and how it can help you write more robust and maintainable code.",
        section_topic_id: "Why Tests-id",
        type: "video",
        videoId: "Why Tests-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Write Good Tests with Mocha",
        section_topic_description: "Learn to use the Mocha framework and the Node.js assert library to write, automate, and organize tests in JavaScript. Automate and Organize Testes, Write Expressive Tests, Documentation Mocha, Learn Mocha",
        section_topic_id: "Write Good Tests with Mocha",
        type: "video",
        videoId: "Write Good Tests with Mocha-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Learn TDD with Mocha",
        section_topic_description: "Learn test-driven development with Mocha. Documentation Chai, ",
        section_topic_id: "Learn TDD with Mocha",
        type: "video",
        videoId: "Learn TDD with Mocha-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Advanced Testing Concepts",
        section_topic_description: "Learn about more advanced concepts used in JavaScript testing. Code coverage, mocking in tests, spies with Sinon",
        section_topic_id: "Advanced Testing Concepts",
        type: "video",
        videoId: "Advanced Testing Concepts-videoId",
        videoLength:12,
      },{
        section_topic_title: "Review Javascript Testing",
        section_topic_description: "Review what was covered in the JavaScript Testing Unit.",
        section_topic_id: "Review Javascript Testing",
        type: "video",
        videoId: "Review Javascript Testing-videoId",
        videoLength:12,
      }
    ],
  },
  {
    sectionTitle: "Async JavaScript and HTTP Requests",
    sectionValue: "Async JavaScript and HTTP Requests",
    sectionNumber:11,
    sectionId: "Async JavaScript and HTTP Requests-Id",
    sectionDescription:
      "Learn what asynchronous code is and how it allows you to use JavaScript to smoothly handle actions that might otherwise block your app and make your users wait.",
    sectionTopics: [
      {
        section_topic_title: "Introduction: Async Javascript and HTTP Requests ",
        section_topic_description: "In this unit, you will learn about asynchronous JavaScript and making HTTP requests to APIs.",
        section_topic_id: "Introduction: Async Javascript and HTTP Requests -id",
        type: "video",
        videoId: "Introduction: Async Javascript and HTTP Requests -videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Basics of Asynchronous Javascript",
        section_topic_description: "Learn about the general programming concepts behind asynchronous JavaScript. Concurrency Model and Event Loop in Javascript",
        section_topic_id: "Basics of Asynchronous Javascript-id",
        type: "video",
        videoId: "Basics of Asynchronous Javascript-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Learn Javascript Syntax: Promises",
        section_topic_description: "Learn how to write asynchronous JavaScript with the Promises Syntax.",
        section_topic_id: "Learn Javascript Syntax: Promises",
        type: "video",
        videoId: "Learn Javascript Syntax: Promises-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Learn Javascript Syntax: Async-Await",
        section_topic_description: "Learn about leveraging asynchronous Promises code using async and await syntax.",
        section_topic_id: "Learn Javascript Syntax: Async-Await",
        type: "video",
        videoId: "Learn Javascript Syntax: Async-Await-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "APIs and HTTP Requests",
        section_topic_description: "Learn about the basics of HTTP requests, REST protocol, what an API is, and JSON data.",
        section_topic_id: "APIs and HTTP Requests",
        type: "video",
        videoId: "APIs and HTTP Requests-videoId",
        videoLength:12,
      },{
        section_topic_title: "Learn Javascript Syntax: Requests",
        section_topic_description: "Learn how to use asynchronous JavaScript techniques to make requests to APIs.",
        section_topic_id: "Learn Javascript Syntax: Requests",
        type: "video",
        videoId: "Learn Javascript Syntax: Requests-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Review: Async Javascript and HTTP Requests",
        section_topic_description: "Review what you just learned in the Async JavaScript and HTTP Requests Unit.",
        section_topic_id: "Review: Async Javascript and HTTP Requests",
        type: "video",
        videoId: "Review: Async Javascript and HTTP Requests-videoId",
        videoLength:12,
      }
    ],
  },
  {
    sectionTitle: "Web Apps",
    sectionValue: "Web Apps",
    sectionNumber:12,
    sectionId: "Web Apps-Id",
    sectionDescription:
      "Confused about web pages, websites, and web apps? Take this unit to differentiate between these different terminologies and what a Single Page Application (SPA) is.",
    sectionTopics: [
      {
        section_topic_title: "Introduction: Web Apps",
        section_topic_description: "See what's covered in the Web Apps Unit.",
        section_topic_id: "Introduction: Web Apps-id",
        type: "video",
        videoId: "Introduction: Web Apps-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "What is a Web App?",
        section_topic_description: "Learn about what web apps are and how they differ from static websites. What is SPA?",
        section_topic_id: "What is a Web App?-id",
        type: "video",
        videoId: "What is a Web App?-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Review: Web Apps",
        section_topic_description: "Review what was covered in the Web Apps Unit.",
        section_topic_id: "Review: Web Apps",
        type: "video",
        videoId: "Review: Web Apps-videoId",
        videoLength:12,
      }
    ],
  },
  {
    sectionTitle: "React, Part I",
    sectionValue: "React, Part I",
    sectionNumber:13,
    sectionId: "React, Part I-Id",
    sectionDescription:
      "Be introduced to React, a popular JavaScript library, to build out the front-end of your apps. This library will build upon your JavaScript knowledge and teach you core React syntax.",
    sectionTopics: [
      {
        section_topic_title: "Introduction: React, Part |",
        section_topic_description: "See what's covered in the React, Part I Unit.",
        section_topic_id: "Introduction: React, Part |-id",
        type: "video",
        videoId: "Introduction: React, Part |-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Javascript Refresher",
        section_topic_description: "Get a refresher on JavaScript ES6 syntax to prepare for working in React.",
        section_topic_id: "Javascript Refresher-id",
        type: "video",
        videoId: "Javascript Refresher-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "The Virtual DOM",
        section_topic_description: "Learn about what the Virtual DOM is and how it helps make React apps more efficient.",
        section_topic_id: "The Virtual DOM",
        type: "video",
        videoId: "The Virtual DOM-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "JSX",
        section_topic_description: "Learn to use JSX, the basic syntax of React.js. Advanced JSX",
        section_topic_id: "JSX",
        type: "video",
        videoId: "JSX-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "React Components",
        section_topic_description: "Learn to make React Components, the building blocks of all React.js applications. Createing a react app",
        section_topic_id: "React Components",
        type: "video",
        videoId: "React Components-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Review: React, Part-|",
        section_topic_description: "Review what was covered in the React, Part I Unit.",
        section_topic_id: "Review: React, Part-|",
        type: "video",
        videoId: "Review: React, Part-|-videoId",
        videoLength:12,
      }
    ],
  },
  {
    sectionTitle: "React, Part II",
    sectionValue: "React, Part II",
    sectionNumber:14,
    sectionId: "React, Part II-Id",
    sectionDescription:
      "Continue with React to learn how different components interact with each other using props, state, hooks, and use React Router, as well as testing with Jest and Enzyme.",
    sectionTopics: [
      {
        section_topic_title: "Introduction: React, Part ||",
        section_topic_description: "See what's covered in the React, Part II Unit.",
        section_topic_id: "Introduction: React, Part ||-id",
        type: "video",
        videoId: "Introduction: React, Part ||-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Components Interacting",
        section_topic_description: "Learn how to make React components interact with one another with state. Components render other components. This.props, this.state, react developer tools, react devtools sandbox.",
        section_topic_id: "Components Interacting-id",
        type: "video",
        videoId: "Components Interacting-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Stateless Components from stateless components",
        section_topic_description: "Learn React programming patterns for mixing components with and without state. Child components update their parents' state. Child components udpate their siblings props. Stateful and stateless programming patterns.",
        section_topic_id: "Stateless Components from stateless components",
        type: "video",
        videoId: "Stateless Components from stateless components-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Lifecycle methods",
        section_topic_description: "Hook actions to specific moments in a component's life. Component lifecycle methods.",
        section_topic_id: "Lifecycle methods",
        type: "video",
        videoId: "Lifecycle methods-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Deploy a React Application with Netlify",
        section_topic_description: "Learn how to create and deploy a React application using the Create React App command-line tool and Netlify. Getting started with Netlify. Deploying a static site with Netlify. Create and share a React App on Github. Deploy your React app on Netlify.",
        section_topic_id: "Deploy a React Application with Netlify",
        type: "video",
        videoId: "Deploy a React Application with Netlify-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Function Components and Hooks",
        section_topic_description: "Learn how to use Hooks in React, a powerful feature of function components. Function Components. The State Hook. The Effect Hook. React Hooks.",
        section_topic_id: "Function Components and Hooks",
        type: "video",
        videoId: "Function Components and Hooks-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Intermediate React",
        section_topic_description: "Learn the most essential remaining React fundamentals. Style. Container components from Presentational Components. PropTypes. React froms. ",
        section_topic_id: "Intermediate React",
        type: "video",
        videoId: "Intermediate React-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "React Router",
        section_topic_description: "Create a seamless user experience by using front-end routing with React Router. Frontend using React Router",
        section_topic_id: "React Router",
        type: "video",
        videoId: "React Router-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Learn React testing with Jest",
        section_topic_description: "Learn to use the Jest framework to write, automate, and organize tests for React code. Getting started with Jest for Javascript Testing. Writing Tests for React Applications Using Jest and Enzyme. Documentation Jest. Documentation Enzyme.",
        section_topic_id: "Learn React testing with Jest",
        type: "video",
        videoId: "Learn React testing with Jest-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Review: React Part ||",
        section_topic_description: "Review what was covered in the React, part || unit.",
        section_topic_id: "Review: React Part ||",
        type: "video",
        videoId: "Review: React Part ||-videoId",
        videoLength:12,
      },
    ],
  },
  {
    sectionTitle: "Redux",
    sectionValue: "Redux",
    sectionNumber:15,
    sectionId: "Redux-Id",
    sectionDescription:
      "Redux is a popular state management library that pairs well with React to create scalable front-end apps that enable you to use a centralized store to pass on data to your components.",
    sectionTopics: [
      {
        section_topic_title: "Introduction: Redux",
        section_topic_description: "See what's covered in the Redux Unit.",
        section_topic_id: "Introduction: Redux-id",
        type: "video",
        videoId: "Introduction: Redux-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Core concepts in Redux",
        section_topic_description: "Learn the concepts underlying all Redux applications, including reducers, state, actions, and the store.",
        section_topic_id: "Core concepts in Redux-id",
        type: "video",
        videoId: "Core concepts in Redux-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Core Redux API",
        section_topic_description: "Learn how to implement Redux state-management into your application by learning the core methods of the Redux API. Intro to core Redux API. Strategies for complex state. Redux API",
        section_topic_id: "Core Redux API",
        type: "video",
        videoId: "Core Redux API-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Connect to React with React Redux",
        section_topic_description: "Learn to access the Redux store to retrieve data and dispatch actions throughout your applications using the react-redux package. The React Redux Library.",
        section_topic_id: "Connect to React with React Redux",
        type: "video",
        videoId: "Connect to React with React Redux-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Refractoring with Redux Toolkit",
        section_topic_description: "Improve your code with Redux Toolkit, an essential package for any Redux application.",
        section_topic_id: "Refractoring with Redux Toolkit",
        type: "video",
        videoId: "Refractoring with Redux Toolkit-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Async Actions with Middleware and Thunks",
        section_topic_description: "Create Redux middleware and thunks to handle asynchronous actions. Redux middleware. Managing Promise Lifecycle Actions. Async Middleware.",
        section_topic_id: "Async Actions with Middleware and Thunks",
        type: "video",
        videoId: "Async Actions with Middleware and Thunks-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Review: Redux",
        section_topic_description: "Review what was covered in the Redux unit.",
        section_topic_id: "Review: Redux",
        type: "video",
        videoId: "Review: Redux-videoId",
        videoLength:12,
      },
    ],
  },
  {
    sectionTitle: "Git and Github, Part ||",
    sectionValue: "Git and Github, Part ||",
    sectionNumber:16,
    sectionId: "Git and Github, Part ||-Id",
    sectionDescription:
      "Further your knowledge of Git and GitHub to streamline your processes for working collaboratively with others through forking, branching, merging conflicts, and making pull requests.",
    sectionTopics: [
      {
        section_topic_title: "Introduction: Git and Github, Part ||",
        section_topic_description: "See what you’ll be learning in the Git and GitHub, Part II Unit.",
        section_topic_id: "Introduction: Git and Github, Part ||-id",
        type: "video",
        videoId: "Introduction: Git and Github, Part ||-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Core concepts in Redux",
        section_topic_description: "Learn the concepts underlying all Redux applications, including reducers, state, actions, and the store.",
        section_topic_id: "Core concepts in Redux-id",
        type: "video",
        videoId: "Core concepts in Redux-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Git Branching",
        section_topic_description: "Learn how to manage different versions of a project with branching.",
        section_topic_id: "Git Branching",
        type: "video",
        videoId: "Git Branching-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Git Teamwork",
        section_topic_description: "An introduction to Git collaborations with remotes, pulling, and pushing.",
        section_topic_id: "Git Teamwork",
        type: "video",
        videoId: "Git Teamwork-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Best practices for Github Repositories",
        section_topic_description: "Learn how to manage your GitHub repository when more people start joining your team. How to write a good pull request? How to use git rebase? Managing a Github Repository. Using a .gitignore file in your github repository.",
        section_topic_id: "Best practices for Github Repositories",
        type: "video",
        videoId: "Best practices for Github Repositories-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Review: Git and Github, part ||",
        section_topic_description: "Review what you just learned in the Git and GitHub, Part II Unit.",
        section_topic_id: "Review: Git and Github, part ||",
        type: "video",
        videoId: "Review: Git and Github, part ||-videoId",
        videoLength:12,
      }
    ],
  },
  {
    sectionTitle: "Introduction to Back-End",
    sectionValue: "Introduction to Back-End",
    sectionNumber:17,
    sectionId: "Introduction to Back-End-Id",
    sectionDescription:
      "Dive into the world of back-end development using your knowledge of Javascript to work in Node.js. You'll implement modules and utilize the Node Package Manager (npm).",
    sectionTopics: [
      {
        section_topic_title: "Introduction: Basics of Back-End Development",
        section_topic_description: "Introduction to the Basics of Back-End Development Unit.",
        section_topic_id: "Introduction: Basics of Back-End Development-id",
        type: "video",
        videoId: "Introduction: Basics of Back-End Development-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "What is a Back-End?",
        section_topic_description: "Learn the basics of what a back-end is. What is server?",
        section_topic_id: "What is a Back-End?-id",
        type: "video",
        videoId: "What is a Back-End?-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Back-end Javascript with NodeJs",
        section_topic_description: "Explore back-end JavaScript with Node.js. Nodejs essentialls.",
        section_topic_id: "Back-end Javascript with NodeJs",
        type: "video",
        videoId: "Back-end Javascript with NodeJs-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Modular Development With NodeJS",
        section_topic_description: "Learn how to use modules in the Node runtime environment, a way to define and utilize reusable logic in your programs. Node modules, Node Package Manager.",
        section_topic_id: "Modular Development With NodeJS",
        type: "video",
        videoId: "Modular Development With NodeJS-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Review: Basics of Back-End Development",
        section_topic_description: "Review what was covered in Basics of Back-End Development Unit.",
        section_topic_id: "Review: Basics of Back-End Development",
        type: "video",
        videoId: "Review: Basics of Back-End Development-videoId",
        videoLength:12,
      }
    ],
  },
  {
    sectionTitle: "Build a Back-end with Express.js",
    sectionValue: "Build a Back-end with Express.js",
    sectionNumber:18,
    sectionId: "Build a Back-end with Express.js-Id",
    sectionDescription:
      "Express.js is a popular Node application framework that enables you to quickly build out core back-end functionality straight out of the box.",
    sectionTopics: [
      {
        section_topic_title: "Introduction: Build a Back-End with Express.js",
        section_topic_description: "Introduction to the Basics of Back-End Development Unit.",
        section_topic_id: "Introduction: Build a Back-End with Express.js-id",
        type: "video",
        videoId: "Introduction: Build a Back-End with Express.js-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Introduction to Express.js",
        section_topic_description: "Learn how to work with Express.js, a popular JavaScript web framework. Introduction to server-side frameworks with Express.js. Express.js API and features.",
        section_topic_id: "Introduction to Express.js-id",
        type: "video",
        videoId: "Introduction to Express.js-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Learn Express: Routes",
        section_topic_description: "Learn how to build an Application Programming Interface (API) in JavaScript using the popular Express.js web framework. Learn express routes, express routers, documentation expressjs routing, setting up postman, how to make API request with postman or cURL",
        section_topic_id: "Learn Express: Routes",
        type: "video",
        videoId: "Learn Express: Routes-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Learn Express: Middleware",
        section_topic_description: "Learn about how to use Express.js middleware to improve an API’s code quality and readability.",
        section_topic_id: "Learn Express: Middleware",
        type: "video",
        videoId: "Learn Express: Middleware-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Review: Build a Back-End with Express.js",
        section_topic_description: "Review what you just learned in the Build a Back-End with Express.js Unit.",
        section_topic_id: "Review: Build a Back-End with Express.js",
        type: "video",
        videoId: "Review: Build a Back-End with Express.js-videoId",
        videoLength:12,
      }
    ],
  },
  {
    sectionTitle: "User Authentication & Authorization",
    sectionValue: "User Authentication & Authorization",
    sectionNumber:19,
    sectionId: "User Authentication & Authorization-Id",
    sectionDescription:
      "Authentication means verifying that your users are who they say they are and authorization determines what permissions they have. Learn how to Implement these key features.",
    sectionTopics: [
      {
        section_topic_title: "Introduction: User Authentication and Authorization",
        section_topic_description: "See what you’ll be learning in the User Authentication and Authorization Unit.",
        section_topic_id: "Introduction: User Authentication and Authorization-id",
        type: "video",
        videoId: "Introduction: User Authentication and Authorization-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Authentication, Authorization, and Encryption",
        section_topic_description: "Authentication, Authorization, and Encryption. Evolution of Authentication.",
        section_topic_id: "Authentication, Authorization, and Encryption-id",
        type: "video",
        videoId: "Authentication, Authorization, and Encryption-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Session Authentication in Express.js",
        section_topic_description: "Learn how to use sessions to implement authentication in Express.js. Sessions & cookies vs local storage. Security Related HTTP headers. Sessions in Express. JSON Web Tokens (JWTs).",
        section_topic_id: "Session Authentication in Express.js",
        type: "video",
        videoId: "Session Authentication in Express.js-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Password Authentication",
        section_topic_description: "Learn about Hashing, Encryption, Encoding, and Obfuscation, how to implement usernames and passwords, and how to encrypt passwords. Hashing vs. Encryption vs. Encoding vs. Obfuscation. Passport.js local authentication. Bcrypt. ",
        section_topic_id: "Password Authentication",
        type: "video",
        videoId: "Password Authentication-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "OAuth 2.0",
        section_topic_description: "Learn how an application can use OAuth 2.0 for authentication and authorization. OAuth 2.0 in Express",
        section_topic_id: "OAuth 2.0",
        type: "video",
        videoId: "OAuth 2.0-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Review User Authentication And Authorization",
        section_topic_description: "Review what you just learned in the User Authentication and Authorization Unit.",
        section_topic_id: "Review User Authentication And Authorization",
        type: "video",
        videoId: "Review User Authentication And Authorization-videoId",
        videoLength:12,
      }
    ],
  },
  {
    sectionTitle: "Back-End and Feature Testing",
    sectionValue: "Back-End and Feature Testing",
    sectionNumber:20,
    sectionId: "Back-End and Feature Testing-Id",
    sectionDescription:
      "Testing on the back-end is also very important. See how test-driven development (TDD) is used to test features as well as the server in this unit.",
    sectionTopics: [
      {
        section_topic_title: "Introduction: Backend and feature testing",
        section_topic_description: "See what you'll learn in the Back-End and Feature Testing Unit.",
        section_topic_id: "Introduction: Backend and feature testing-id",
        type: "video",
        videoId: "Introduction: Backend and feature testing-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Feature Testing with TDD",
        section_topic_description: "Learn feature development for a full-stack web application by writing JavaScript tests that use headless browsing. Out-side in test driven development. Introduction to headless browser testing. TDD feature level tests. Documentation PhantomJS.",
        section_topic_id: "Feature Testing with TDD-id",
        type: "video",
        videoId: "Feature Testing with TDD-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Server Testing with TDD",
        section_topic_description: "Learn to use test-driven development to create a JavaScript server using the Express.js framework. Server testing stack. Documentation jsDom. API testing using super Test. Documentation superTest. Server testing stack. server testing patterns. ",
        section_topic_id: "Server Testing with TDD",
        type: "video",
        videoId: "Server Testing with TDD-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Review: Backend and feature Testing.",
        section_topic_description: "Review what was covered in the Back-End and Feature Testing Unit.",
        section_topic_id: "Review: Backend and feature Testing.",
        type: "video",
        videoId: "Review: Backend and feature Testing.-videoId",
        videoLength:12,
      }
    ],
  },
  {
    sectionTitle: "Connecting Front-End to Back-End",
    sectionValue: "Connecting Front-End to Back-End",
    sectionNumber:21,
    sectionId: "Connecting Front-End to Back-End-Id",
    sectionDescription:
      "You've learned front-end and back-end development, now learn how to combine the two to build out a full-stack app. You'll also learn how to structure your apps using MVC architecture.",
    sectionTopics: [
      {
        section_topic_title: "Introduction: Connecting Front-End to Back-End",
        section_topic_description: "See what you’ll be learning in the Connecting Front-End to Back-End Unit.",
        section_topic_id: "Introduction: Connecting Front-End to Back-End-id",
        type: "video",
        videoId: "Introduction: Connecting Front-End to Back-End-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Connecting Front-End to Back-End",
        section_topic_description: "Learn about client-side and server-side rendering and create REST API endpoints to connect the front-end to the back-end. Code Generation. Creating REST API endpoints. Server-Side API Calls to External APIs.",
        section_topic_id: "Connecting Front-End to Back-End-id",
        type: "video",
        videoId: "Connecting Front-End to Back-End-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "How to Structure your Apps?",
        section_topic_description: "Get an introduction to the Model, View, Controller design pattern and create full-stack apps using MVC architecture.",
        section_topic_id: "How to Structure your Apps?",
        type: "video",
        videoId: "How to Structure your Apps?-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Review: Connecting Front-End to Back-End",
        section_topic_description: "Review what you just learned in the Connecting Front-End to Back-End Unit.",
        section_topic_id: "Review: Connecting Front-End to Back-End",
        type: "video",
        videoId: "Review: Connecting Front-End to Back-End-videoId",
        videoLength:12,
      }
    ],
  },
  {
    sectionTitle: "Web Security Fundamentals",
    sectionValue: "Web Security Fundamentals",
    sectionNumber:22,
    sectionId: "Web Security Fundamentals-Id",
    sectionDescription:
      "Web security is becoming increasingly important. Learn the fundamentals of what web security is and prevention techniques for common threats.",
    sectionTopics: [
      {
        section_topic_title: "Introduction: Web Security Fundamentals",
        section_topic_description: "See what you’ll be learning in the Web Security Fundamentals Unit.",
        section_topic_id: "Introduction: Web Security Fundamentals-id",
        type: "video",
        videoId: "Introduction: Web Security Fundamentals-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Web Security",
        section_topic_description: "Learn about why web security is important for a web application. Web Security: Not an Add on. 2017 OWASP Top 10. ",
        section_topic_id: "Web Security-id",
        type: "video",
        videoId: "Web Security-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Review: Web Security Fundamentals",
        section_topic_description: "Review what you just learned in the Web Security Fundamentals Unit.",
        section_topic_id: "Review: Web Security Fundamentals-id",
        type: "video",
        videoId: "Review: Web Security Fundamentals-videoId",
        videoLength:12,
      }
    ],
  },
  {
    sectionTitle: "Data Security",
    sectionValue: "Data Security",
    sectionNumber:23,
    sectionId: "Data Security-Id",
    sectionDescription:
      "Data should only be shared with its intended recipients. Learn to secure your data using Transport Layer Security (TLS), Role-Based Access Control (RBAC), and more!",
    sectionTopics: [
      {
        section_topic_title: "Introduction: Data Security",
        section_topic_description: "See what you’ll be learning in the Data Security Unit.",
        section_topic_id: "Introduction: Data Security-id",
        type: "video",
        videoId: "Introduction: Data Security-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Transport Layer Security(TLS)",
        section_topic_description: "Learn about Transport Layer Security (TLS): one of the protocols that runs the modern internet.",
        section_topic_id: "Transport Layer Security(TLS)-id",
        type: "video",
        videoId: "Transport Layer Security(TLS)-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Role-Based Access Control (RBAC)",
        section_topic_description: "Learn the basics of designing a Role-Based Access Control (RBAC) system.",
        section_topic_id: "Role-Based Access Control (RBAC)-id",
        type: "video",
        videoId: "Role-Based Access Control (RBAC)-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Authentication and Authorization in Postgres",
        section_topic_description: "Learn how to manage authentication and authorization in Postgres.",
        section_topic_id: "Authentication and Authorization in Postgres-id",
        type: "video",
        videoId: "Authentication and Authorization in Postgres-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Managing Environment Variables, API Keys, and Files",
        section_topic_description: "Secure environment variables, API keys, and files from unauthorized access. Documentation: dotenv. ",
        section_topic_id: "Managing Environment Variables, API Keys, and Files-id",
        type: "video",
        videoId: "Managing Environment Variables, API Keys, and Files-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Review: Data Security",
        section_topic_description: "Review what you just learned in the Data Security Unit.",
        section_topic_id: "Review: Data Security-id",
        type: "video",
        videoId: "Review: Data Security-videoId",
        videoLength:12,
      },
    ],
  },
  {
    sectionTitle: "Common Attacks on Web Applications",
    sectionValue: "Common Attacks on Web Applications",
    sectionNumber:24,
    sectionId: "Common Attacks on Web Applications-Id",
    sectionDescription:
      "There are common patterns that are used to attack web apps. Learn how to prevent the most common attacks like cross-site scripting (XSS), SQL injections, and more.",
    sectionTopics: [
      {
        section_topic_title: "Introduction: Common Attacks on Web Applications",
        section_topic_description: "See what you’ll be learning in the Common Attacks on Web Applications Unit.",
        section_topic_id: "Introduction: Common Attacks on Web Applications-id",
        type: "video",
        videoId: "Introduction: Common Attacks on Web Applications-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Prevent Cross-Site Scripting (XSS) Attacks",
        section_topic_description: "Learn how Cross-Site Scripting attacks work and how to prevent them. Cross-Site Scripting attacks. What is CORS? Preventing Cross-Site Scripting (XSS) Attacks.",
        section_topic_id: "Prevent Cross-Site Scripting (XSS) Attacks-id",
        type: "video",
        videoId: "Prevent Cross-Site Scripting (XSS) Attacks-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Preventing Cross-Site Request Forgery (CSRF) Attacks.",
        section_topic_description: "Learn what CSRF attacks are and the primary techniques to mitigate them.",
        section_topic_id: "Preventing Cross-Site Request Forgery (CSRF) Attacks.-id",
        type: "video",
        videoId: "Preventing Cross-Site Request Forgery (CSRF) Attacks.-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Preventing SQL Injection Attacks.",
        section_topic_description: "Learn how to spot and prevent SQL injection attacks.",
        section_topic_id: "Preventing SQL Injection Attacks.-id",
        type: "video",
        videoId: "Preventing SQL Injection Attacks.-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Defensive Coding in Javascript",
        section_topic_description: "Learn and practice some techniques for keeping code secure.",
        section_topic_id: "Defensive Coding in Javascript-id",
        type: "video",
        videoId: "Defensive Coding in Javascript-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Remediation and Incident Response",
        section_topic_description: "Learn the basics of Remediation and Incident Response.",
        section_topic_id: "Remediation and Incident Response-id",
        type: "video",
        videoId: "Remediation and Incident Response-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Off-platform Project: ACME Bank",
        section_topic_description: "Defend a Node application from SQL Injection, Cross-Site Scripting (XSS), & Cross-Site Request Forgery (CSRF) attacks.",
        section_topic_id: "Off-platform Project: ACME Bank-id",
        type: "video",
        videoId: "Off-platform Project: ACME Bank-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Review: Common Attacks on Web Application",
        section_topic_description: "Review what you just learned in the Common Attacks on Web Applications Unit.",
        section_topic_id: "Review: Common Attacks on Web Application-id",
        type: "video",
        videoId: "Review: Common Attacks on Web Application-videoId",
        videoLength:12,
      },
    ],
  },
  {
    sectionTitle: "Fundamentals of Operating Systems",
    sectionValue: "Fundamentals of Operating Systems",
    sectionNumber:25,
    sectionId: "Fundamentals of Operating Systems-Id",
    sectionDescription:
      "Operating systems play a key role in how browsers, apps, and user interactions play out. Learn about core operating system functionality to get an under-the-hood look at the OS.",
    sectionTopics: [
      {
        section_topic_title: "Introduction: Fundamentals of Operating Systems.",
        section_topic_description: "See what you’ll be learning in the Fundamentals of Operating Systems Unit.",
        section_topic_id: "Introduction: Fundamentals of Operating Systems.-id",
        type: "video",
        videoId: "Introduction: Fundamentals of Operating Systems.-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Operating System Basics.",
        section_topic_description: "Learn about how computers process data, the important hardware in every computer, and the basic functionalities of an operating system.",
        section_topic_id: "Operating System Basics.-id",
        type: "video",
        videoId: "Operating System Basics.-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Processes and Threads.",
        section_topic_description: "Learn about how processes and threads work in an operating system.",
        section_topic_id: "Processes and Threads.-id",
        type: "video",
        videoId: "Processes and Threads.-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Process Scheduling",
        section_topic_description: "Learn how process scheduling is used to manage multiple active processes!",
        section_topic_id: "Process Scheduling-id",
        type: "video",
        videoId: "Process Scheduling-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Synchronization + Deadlock",
        section_topic_description: "Learn about synchronization and how it organizes the use of shared data amongst threads.",
        section_topic_id: "Synchronization + Deadlock-id",
        type: "video",
        videoId: "Synchronization + Deadlock-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Memory Management",
        section_topic_description: "Learn about the techniques the operating system uses to manage memory.",
        section_topic_id: "Memory Management-id",
        type: "video",
        videoId: "Memory Management-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "File Systems.",
        section_topic_description: "Learn about how the operating system uses filesystems to store, organize, and retrieve data.",
        section_topic_id: "File Systems.-id",
        type: "video",
        videoId: "File Systems.-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "I/O Systems",
        section_topic_description: "Learn about how the operating system manages IO devices. IO hardware, IO software, ",
        section_topic_id: "I/O Systems-id",
        type: "video",
        videoId: "I/O Systems-videoId",
        videoLength:12,
      },
      {
        section_topic_title: "Review: Fundamentals of Operating System",
        section_topic_description: "Review what you just learned in the Fundamentals of Operating Systems Unit.",
        section_topic_id: "Review: Fundamentals of Operating System-id",
        type: "video",
        videoId: "Review: Fundamentals of Operating System-videoId",
        videoLength:12,
      },
    ],
  },
];

// course data: web security
